apiVersion: ENC[AES256_GCM,data:Tbs=,iv:UOrMNRKhgefkLa5t0mnTfjWY0+3Zkj3SL4Syf7UUUBI=,tag:6R6bmn+MvskgDs85mnSKYQ==,type:str]
kind: ENC[AES256_GCM,data:2+OkQMco,iv:2EAJap0QEWLo72DMRSzpFMY+s3JMkprZVgP4D4hhfyc=,tag:WQnBfJUEpMX1iRDRsqYMSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Lp/DDXDHEd722ezCuq8rcAtK,iv:4Yi3sJqO06MaZPLAtYM5fqTJTHUv2BpL9gBO3GVtZtI=,tag:7GGMrV9KbJqPbvBKgTxujQ==,type:str]
    namespace: ENC[AES256_GCM,data:AUqz4oU=,iv:R+4mBwd7VRHBtPctZm+oRX1B74wY4SpfG9rulQHbwcY=,tag:4gjTCpjSYWNzoCcLNg4/Zg==,type:str]
type: ENC[AES256_GCM,data:e/B8FsDU,iv:xZPhEkKOndfW4VqCYpsUVNVKAOgCgzkqHI2y3KvYiGw=,tag:YP7QIHxI5vdNO3b9s95QDg==,type:str]
data:
    username: ENC[AES256_GCM,data:l/rEEisRTQn54Lms,iv:u5QFPIDbFhr0eDDcgF9Gp4RBe009i3cxN0F7yrZKHLw=,tag:B1XSLKW9V8cAR2H0ID4K+g==,type:str]
    password: ENC[AES256_GCM,data:jr7d+o/DS/Aa+o3MPU9HqBsytx/TxduTrNerzA==,iv:N+tkc15685/yBtbxG2yVVj/GuET5/iCSOKRmfyc2/qY=,tag:om+Fcr5TqYux3hcOmUUA5Q==,type:str]
sops:
    age:
        - recipient: age15xez8pcmgg3daxpuqnye9ewawvzjtallheddcrq88ph573yle3nsr5hdq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWY1YmpqUy9ndnp6UjFx
            UWlnVHdTTjJRdnVUUWkzbUU5OVBzSnV3Z0FFCk1QTnBucHpta3VFRUV2dnZLY0lN
            dWppWjJTMzJMUGxtMnU0c2FtODFSelEKLS0tIHM5ZmhVdnlocXl5U210VUZlSXpq
            a3RZK2hTSTR2RHd4TnBUZjRXZUhyd0EKooYzy9tYU1tx6hUrlu+mZW0KahoDjbO8
            QiHFGCZQuw16WZUBnsjLWzwupIC5iOgb+iEHu5M9g80p4bZpreyqjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:45:39Z"
    mac: ENC[AES256_GCM,data:tV+NKWTRNt2sOr8zr12dldUfPRq//ePSjU0M7XeLTPCAjv+4JE5RhFnEa/wmL8L4D9u46evp3nE6LjO34rZYCkyabOtsMxXs40+PuYugUiFVxqEQ6tBrIJS1THAhLj+a4p5I3D+SyAiykygr8IvfWnngTa2YF0HK0uCeB+pnGaM=,iv:U0068Zqh8i+vm7fP4PdBNr5u9qMKWpd3zlr5iu7jyS4=,tag:Ox+TBvu8TwMwDip+axjvVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
