apiVersion: v1
kind: Service
metadata:
  name: kubernetes-mcp
  namespace: infra-mcp
spec:
  type: NodePort
  selector:
    app: kubernetes-mcp
  ports:
    - port: 3402
      targetPort: 3402
      nodePort: 30342
      name: http
