apiVersion: ENC[AES256_GCM,data:Gtc=,iv:BuIiTyJ+HM7xi0N47V/kc1cp2dbr66HmudlfSyDlP3A=,tag:pysGD24foY7An1T5gMKXRg==,type:str]
kind: ENC[AES256_GCM,data:QRsIXfeb,iv:e95HWTNprwFPT5YDJLZzw5esk7NEra9BDxgtW/6bVdw=,tag:PGZtoePAvKPYNm0ox35zGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TK+mlIrACsKe8fpMEc2JuE8=,iv:QkajhkDPZ9uyDNy+NrI3KhfW01NAx9xgqDpgkqxU7sk=,tag:BoSIk+mh2oINv99UmOeOsQ==,type:str]
    namespace: ENC[AES256_GCM,data:fETUJwlIm9pH,iv:N8PIAR2iKM1EbsmVm9IgwtmWFuip5lxYrb9Ru54fJZk=,tag:PkKMc31GZe/fpsYCdLlbKA==,type:str]
type: ENC[AES256_GCM,data:0ZBT2+YE,iv:fRiTxl/gqYwUMz2hUzPZ754M7Uw92+K1B1y/7zsNZ7E=,tag:AQgeO7ZU71KoxOBGMENfPQ==,type:str]
stringData:
    GITEA_ACCESS_TOKEN: ENC[AES256_GCM,data:IKrUok7SQPNk+rG6vnu3B6u78+51lG8O9WRhYGVXQUzbhduHnpkjxQ==,iv:7rjZjgXJ5JjENkbcHxqqp9pQmcBpqyvJLyWR/ExPbdw=,tag:vKoRmpemQUtArEEAZ3tOCQ==,type:str]
sops:
    age:
        - recipient: age15xez8pcmgg3daxpuqnye9ewawvzjtallheddcrq88ph573yle3nsr5hdq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOUR0Z1orR2FLdWxzWWhF
            MmVGTHpEQUhsSExmQkZJYkR0bXIvTWVRc0dzCkx1MC9YMERPTFluOTd3ZUlhaTQw
            SDZpOFdBNUo5TDFQdHlRWWJoSUozUEUKLS0tIFYySUc5R1JTRXF4dDhSbkE5UTdR
            N2ExT1JXRS9FSE5xOGpvWjUzMmpXMGMKX+NYIacFTegeKM20ED68VJlgBQt7F1+v
            c2MQoa1c7OmaC8LUx7FUj9OdyaagnQv2iWPjdPRRv/1bbabSeNkFLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:19:17Z"
    mac: ENC[AES256_GCM,data:oDWU95xjGe1RKgwzPAzOsb/lmIbuhcQToOgre9HVtJ++Foqk+/0keVAqL/sX+G6rBmeAaahBW99tb9985K1L4xEafV/AGmG0aIH71IlSiG2JRv3G3PX9U4jZR1gcAKoPl+9YWjxFhVqahdZfiVkBnyEJ3iatpvyiavPQDBe8DqQ=,iv:7UsE49+KJE53zki2W8fQcsj5bsadVvyBb5aGt/f4hx0=,tag:qZ8UTmqFzhkrACpRrsE1mQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
