apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      hostPID: true
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      priorityClassName: system-node-critical
      containers:
      - image: nvcr.io/nvidia/k8s-device-plugin:v0.17.1
        name: nvidia-device-plugin-ctr
        securityContext:
          privileged: true
        env:
        - name: LD_LIBRARY_PATH
          value: /host-lib
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: nvidia-ml
          mountPath: /host-lib/libnvidia-ml.so.1
        - name: nvidia-ml-versioned
          mountPath: /host-lib/libnvidia-ml.so.595.58.03
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: nvidia-ml
        hostPath:
          path: /usr/lib/libnvidia-ml.so.1
      - name: nvidia-ml-versioned
        hostPath:
          path: /usr/lib/libnvidia-ml.so.595.58.03
